#prod first
version: '3.3'
services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - /root/tmp/db:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  web:
    build: ./app
    image: '424385760710.dkr.ecr.us-east-2.amazonaws.com/vergeman/abrepo:latest'
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && rake tmp:cache:clear && bundle exec rails s -p 8081 -b '0.0.0.0'"
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - db
