#dev settings - stubs for now
version: '3.4'
services:

  pgbouncer:
    environment:
      - POSTGRESQL_DATABASE=abrepo_www_dev
      - PGBOUNCER_DATABASE=abrepo_www_dev

  pg1:
    #chown -R 1001:1001 /db
    volumes:
      - ./db/postgres:/bitnami/postgresql
      - ./db/pgbackrest.conf:/etc/pgbackrest.conf
      - ./db/postgresql_custom.conf:/opt/bitnami/postgresql/conf/conf.d/postgresql_custom.conf
      - ./db/archive.conf:/opt/bitnami/postgresql/conf/conf.d/archive.conf
    environment:
      - PGBACKREST_REPO1_PATH=/tmpdb/pgbackrest
      - PGBACKREST_LOG_PATH=/tmpdb/pgbackrest
      - PGBACKREST_REPO2_S3_BUCKET=abrepo-dev-pg1-pgbackrest

  web:
    build: ./app
    healthcheck:
      test: ""
    volumes:
      # NB: this will require gem install, webpacker build, db perms
      # for dev environment (since it overrides)
      - ./app:/app
    environment:
      - RAILS_ENV=development
      - APPLICATION_HOST=http://localhost
      - FILE_HOST=

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    environment:
      - NGINX_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./app/public:/app/public
      - /home/vergeman/dev/ab/screenshots:/app/public/screenshots
      - ./app/app/assets:/app/app/assets
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
    #needed for build
    depends_on:
      - web

  haproxy:
   volumes:
     - ./haproxy/haproxy_dev.cfg:/bitnami/haproxy/conf/haproxy.cfg

volumes:
  pg1data:
    driver: local
  portainer_data:
    driver: local
