#dev settings - stubs for now
version: '3.4'
services:

  pgbouncer:
    environment:
      - POSTGRESQL_DATABASE=abrepo_www_dev
      - PGBOUNCER_DATABASE=abrepo_www_dev

  pg1:
    #chown -R 1001:1001 /db
    volumes:
      - ./db/postgres:/bitnami/postgresql
      - ./db/pgbackrest.conf:/etc/pgbackrest.conf
      - ./db/postgresql_custom.conf:/opt/bitnami/postgresql/conf/conf.d/postgresql_custom.conf
      # Read README.md for explicit restore ops
      #- ./db/archive.conf:/opt/bitnami/postgresql/conf/conf.d/archive.conf
      #- ./db/run.sh:/opt/bitnami/scripts/postgresql/run.sh
    environment:
      - PGBACKREST_REPO1_PATH=/mnt/abrepo/pgbackrest
      - PGBACKREST_LOG_PATH=/mnt/abrepo/pgbackrest
      - PGBACKREST_REPO2_S3_BUCKET=abrepo-dev-pg1-pgbackrest

  web:
    build: ./app
    healthcheck:
      test: ""
    volumes:
      # NB: this will require gem install, webpacker build, db perms
      # for dev environment (since it overrides)
      - ./app:/app
    env_file:
      - .env.dev
    deploy:
      replicas: 1


  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./app/public:/app/public
      - /home/vergeman/dev/ab/screenshots:/app/public/screenshots
      - ./app/app/assets:/app/app/assets
      - ./nginx/nginx.conf.dev.template:/etc/nginx/templates/default.conf.template

    # needed for build
    depends_on:
      - web

  haproxy:
    ports:
      - "80:8888"
    volumes:
      - ./haproxy/haproxy_dev.cfg:/usr/local/etc/haproxy/haproxy.cfg

volumes:
  pg1data:
    driver: local
  portainer_data:
    driver: local
