version: '3.4'
services:
#
# REPLICA DB - traefik disabled
#
# We exclude to have the service available, but if we add a replica,
# include this in the deployed, singular stack.yml.
#
# Want to avoid messy state of what's deployed from which file:
# single file, single state, keep it simple.
#
#
# Failover:
# 0. promote replica to primary via shell: pg_ctl promote -D <pg db path>
# 0. set proxy to new primary
#
# 1. change POSTGRESQL_REPLICATION_MODE=master/slave on each service
# 2. toggle traefik.enable = true/false (traefik enabled true only on master)
# 3. rename volume in cloud, or set new volume here
#
  pg2:
    image: 'bitnami/postgresql:latest'
    env_file:
      - .env.db
    volumes:
      - pg2data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.hostname == db-2
      labels:
        - "traefik.enable=false"
        - "traefik.tcp.routers.to-db.entrypoints=db"
        - "traefik.tcp.routers.to-db.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.to-db.service=primary"
        - "traefik.tcp.services.primary.loadbalancer.server.port=5432"

volumes:
  pg2data:
    driver: rexray/dobs
    driver_opts:
      size: 1
