apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: abrepo-nginx
  name: abrepo-nginx
  namespace: abrepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abrepo-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: abrepo-nginx
    spec:
      affinity:
        nodeAffinity:
          # Hard requirement: Avoid `node.kubernetes.io=cntrl`
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/class_id
                    operator: NotIn
                    values:
                      - cntrl
          # Soft preference: Prefer `node.kubernetes.io=app`
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/class_id
                    operator: In
                    values:
                      - app
            # Lower priority preference for `node.kubernetes.io=gen`
            - weight: 10
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/class_id
                    operator: In
                    values:
                      - gen
      imagePullSecrets:
        - name: regcred
      containers:
        - image: ${IMAGE_REPO}/abrepo/abnginx:${GIT_COMMIT}
          name: abrepo-nginx
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: nginx.conf
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"        # Minimum memory requested
            limits:
              memory: "96Mi"        # Maximum memory allowed
          envFrom:
          - configMapRef:
              name: abrepo-nginx-configmap
      volumes:
        - name: nginx-config
          configMap:
            name: abrepo-nginx-configmap
