require "test_helper"
require "minitest/mock"

class CheckoutControllerTest < ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers
  include CheckoutHelper

  def before_setup
    skip "Skipping all tests in this class: Stripe removal"
  end

  def setup
    @user = users(:user_two)

    @stripe_price = {
      'object' => 'list',
      'data' => [
        {
          'id' => 'price_123',
          'lookup_key' => 'basic-monthly',
          'nickname' => 'Monthly Subscription',
          'product' => 'prod_abc',
          'unit_amount' => 1234,
          'unit_amount_decimal' => "1234",
          "recurring" => {
                         "aggregate_usage": nil,
                         "interval":"month",
                         "interval_count":1,
                         "meter": nil,
                         "trial_period_days": nil,
                         "usage_type":"licensed"
                       },
        }
      ],
      'has_more' => false,
      'url' => '/v1/prices'
    }

    @mock_stripe_price = Stripe::Util.convert_to_stripe_object(@stripe_price, "xyz")


    @stripe_price_params = {
      lookup_keys: [@stripe_price['data'][0]['lookup_key'], ENV['STRIPE_DEFAULT_LOOKUP_KEY']]
    }

    # when Stripe::Checkout::Session.create is called, devise has already created a user
    # but we can't know this value ahead of time to pass as a stub to the
    # Stripe::Checkout::Session.create
    #
    # see TRUNCATE users RESTART to force newly created user id to 1

    @checkout_session_params = {
      customer: nil,
      customer_email: nil,
      client_reference_id: 1,
      subscription_data: {metadata: {abrepo_email: "test@example.com", user_id: 1 }},
      success_url: "http://www.example.com/checkout/success?session_id={CHECKOUT_SESSION_ID}",
      cancel_url: "http://www.example.com/#pricing",
      payment_method_types: ["card"],
      mode: "subscription",
      allow_promotion_codes: true,
      line_items: [{quantity: 1, price: "price_123"}]
    }

    @checkout_session_return = Stripe::Util.convert_to_stripe_object(
      { id: 'session_123', url: 'http://example.com/checkout' }, "xyz"
    )

  end

  test "should redirect to root if user signed in on account" do
    sign_in @user
    get checkout_account_path
    assert_redirected_to root_path(anchor: "pricing")
  end


  test "should render new registration view if user not signed in" do
    sign_out @user
    Rails.cache.clear

    expected_params = {
      lookup_keys: [@stripe_price['data'][0]['lookup_key'], ENV['STRIPE_DEFAULT_LOOKUP_KEY']]
    }

    mock = Minitest::Mock.new
    mock.expect(:call, @mock_stripe_price, [expected_params])

    Stripe::Price.stub(:list, mock) do
      get checkout_account_path
      assert_response :success
      assert_not_nil assigns(:price_key)
      assert_not_nil assigns(:price)
      assert_equal assigns(:price).id, 'price_123'
      assert_template 'checkout/account'
    end

    assert mock.verify
  end


  test "should render json errors on create when resource invalid" do
    post checkout_user_create_path, params: { user: { email: '', password: 'password' } }
    assert_response :bad_request
    json_response = JSON.parse(response.body)
    assert_not json_response['user']['ok']
    assert json_response['user']['errors']['messages'].present?
  end


  test "should create user and return stripe session on valid create" do
    sign_out @user
    Rails.cache.clear

    #
    # users are created visting post checkout_user_create_path,
    # so user.id can be inconsistent (generated by db) vs mock values.
    # we use "TRUNCATE users RESTART IDENTITY CASCADE" to enforce id restart at 1
    #
    ActiveRecord::Base.connection.execute("TRUNCATE users RESTART IDENTITY CASCADE")


    stripe_price_mock = Minitest::Mock.new
    stripe_price_mock.expect(:call, @mock_stripe_price, [@stripe_price_params])

    # splat, because Session create method takes named parameters
    checkout_session_mock = Minitest::Mock.new
    checkout_session_mock.expect(:call, @checkout_session_return, **@checkout_session_params)

    Stripe::Price.stub(:list, stripe_price_mock) do

      Stripe::Checkout::Session.stub(:create, checkout_session_mock) do

        post checkout_user_create_path, params: {
               lookup_key: 'basic-monthly',
               data: {:price_key => 'basic-monthly'},
               user: { email: "test@example.com", password: 'password' }
             }
        assert_response :success
        json_response = JSON.parse(response.body)

        assert json_response['user']['ok']
        assert json_response['stripe']['ok']
        assert json_response['stripe']['sessionId'].present?
      end
    end

    assert stripe_price_mock.verify
    assert checkout_session_mock.verify
  end

  test "should handle stripe error gracefully on create" do

    Rails.cache.clear

    stripe_price_mock = Minitest::Mock.new
    stripe_price_mock.expect(:call, @mock_stripe_price, [@stripe_price_params])

    raises_exception = -> (a) { raise Stripe::StripeError.new("error") }

    Stripe::Price.stub(:list, stripe_price_mock) do
      Stripe::Checkout::Session.stub(:create, raises_exception) do
        post checkout_user_create_path, params: {
               lookup_key: 'no key',
               data: {:price_key => 'basic-monthly'},
               user: { email: 'test@example.com', password: 'password' }
             }
        assert_response :bad_request
        json_response = JSON.parse(response.body)
        assert_not json_response['stripe']['ok']
        assert json_response['stripe']['errors']['messages'].include?("Payment provider error. Please try again.")
      end
    end
  end

  test "should redirect to checkout_account_path on new" do
    get new_user_registration_path, params: { lookup_key: "test"}
    assert_redirected_to checkout_account_path({ lookup_key: "test"})
  end

end
